# Generated by Django 4.2.3 on 2023-07-18 11:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomtokengenerator',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='randomtokengenerator',
            name='token',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
