# Generated by Django 4.2.3 on 2023-07-18 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('admin_home', '0003_alter_randomtokengenerator_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomtokengenerator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
