# Generated by Django 4.2.3 on 2023-07-19 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0004_alter_randomtokengenerator_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='randomtokengenerator',
            name='coupon',
            field=models.CharField(default='asdlkjf', max_length=20),
        ),
        migrations.AddField(
            model_name='randomtokengenerator',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='randomtokengenerator',
            name='token',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
