# Generated by Django 4.2.3 on 2023-07-19 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0005_randomtokengenerator_coupon_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomtokengenerator',
            name='coupon',
            field=models.CharField(max_length=20),
        ),
    ]
