# Generated by Django 4.2.3 on 2023-07-19 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0006_alter_randomtokengenerator_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomtokengenerator',
            name='coupon',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
