# Generated by Django 4.2.3 on 2023-07-19 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0007_alter_randomtokengenerator_coupon'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randomtokengenerator',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='randomtokengenerator',
            name='is_verified',
        ),
    ]
