# Generated by Django 4.2.3 on 2023-08-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0009_psychologicaltasks_taskitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psychologicaltasks',
            name='title',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='taskitems',
            name='title',
            field=models.CharField(unique=True),
        ),
    ]
