# Generated by Django 4.2.3 on 2023-08-08 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0010_alter_psychologicaltasks_title_alter_taskitems_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskitems',
            name='image',
        ),
    ]
