# Generated by Django 4.2.3 on 2023-08-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0013_callbackreqs'),
    ]

    operations = [
        migrations.AddField(
            model_name='callbackreqs',
            name='is_contacted',
            field=models.BooleanField(default=False),
        ),
    ]
