# Generated by Django 4.2.3 on 2023-08-13 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_home', '0014_callbackreqs_is_contacted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CallBackReqs',
        ),
    ]
