# Generated by Django 4.2.3 on 2023-07-13 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counseloreducation',
            options={'verbose_name_plural': "Counselor's Education"},
        ),
        migrations.AlterField(
            model_name='counselorprofile',
            name='state',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
