# Generated by Django 4.2.3 on 2023-08-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0002_alter_counseloreducation_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counseloreducation',
            name='year',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
