# Generated by Django 4.2.3 on 2023-08-03 04:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counselor', '0003_counseloreducation_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseloreducation',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
