# Generated by Django 4.2.3 on 2023-08-03 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0004_alter_counseloreducation_counselor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseloreducation',
            name='qualification',
            field=models.CharField(max_length=100),
        ),
    ]
