# Generated by Django 4.2.3 on 2023-08-03 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0005_alter_counseloreducation_qualification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseloreducation',
            name='certificate',
            field=models.FileField(upload_to='certificates'),
        ),
        migrations.AlterField(
            model_name='counseloreducation',
            name='year',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
