# Generated by Django 4.2.3 on 2023-08-03 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0006_alter_counseloreducation_certificate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counseloreducation',
            name='certificate',
            field=models.ImageField(upload_to='certificates'),
        ),
    ]
