# Generated by Django 4.2.3 on 2023-08-03 08:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counselor', '0008_alter_counseloreducation_certificate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counselorexperience',
            options={'verbose_name_plural': "Counselor's Experience"},
        ),
        migrations.AlterField(
            model_name='counselorexperience',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
