# Generated by Django 4.2.3 on 2023-08-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0009_alter_counselorexperience_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='counselorexperience',
            name='certificate',
            field=models.ImageField(null=True, upload_to='exp_certificates'),
        ),
        migrations.AlterField(
            model_name='counseloreducation',
            name='certificate',
            field=models.ImageField(upload_to='edu_certificates/'),
        ),
    ]
