# Generated by Django 4.2.3 on 2023-08-07 12:13

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_service_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counselor', '0011_alter_counselorexperience_certificate'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CounselorProfile',
            new_name='CounselorAccount',
        ),
    ]
