# Generated by Django 4.2.3 on 2023-08-07 15:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_service_icon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counselor', '0012_rename_counselorprofile_professionalprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='CounselorAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.BigIntegerField(default=600)),
                ('state', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('specialization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.service')),
            ],
        ),
    ]
