# Generated by Django 4.2.3 on 2023-07-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_profile_image_account_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='role',
            field=models.CharField(choices=[('user', 'user'), ('counselor', 'counselor'), ('admin', 'admin')], default='user', max_length=30),
        ),
    ]
