# Generated by Django 4.2.3 on 2023-07-16 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_account_role'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='is_google',
            field=models.BooleanField(default=False),
        ),
    ]
