# Generated by Django 4.2.3 on 2023-07-16 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_managers_account_is_google'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
    ]
