# Generated by Django 4.2.3 on 2023-08-16 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.TimeField()),
                ('end', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='appointments',
            old_name='date',
            new_name='session_date',
        ),
        migrations.AddField(
            model_name='appointments',
            name='amount_paid',
            field=models.PositiveBigIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='appointments',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='appointments',
            name='is_paid',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('Attended', 'Attended'), ('Pending', 'Pending'), ('Not attended', 'Not attended')], default='Attended', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointments',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='booking.timeslots'),
        ),
        migrations.DeleteModel(
            name='Slots',
        ),
    ]
