# Generated by Django 4.2.3 on 2023-08-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
