# Generated by Django 4.2.3 on 2023-08-16 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_timeslots_rename_date_appointments_session_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='payment',
        ),
    ]
