# Generated by Django 4.2.3 on 2023-08-31 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_appointments_link_alter_meetlink_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meetlink',
            name='link',
            field=models.CharField(max_length=100),
        ),
    ]
