# Generated by Django 4.2.3 on 2023-08-16 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_remove_appointments_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('Attended', 'Attended'), ('Pending', 'Pending'), ('Not attended', 'Not attended')], default='Pending', max_length=20),
        ),
    ]
