# Generated by Django 4.2.3 on 2023-08-17 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counselor', '0013_counseloraccount'),
        ('booking', '0005_timeslots_counselor_timeslots_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslots',
            name='counselor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='counselor.counseloraccount'),
        ),
    ]
