# Generated by Django 4.2.3 on 2023-08-17 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_appointmentpayments_is_booked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentpayments',
            name='is_booked',
        ),
    ]
