# Generated by Django 4.2.3 on 2023-08-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_appointmentpayments_is_booked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointments',
            name='status',
            field=models.CharField(choices=[('Attended', 'Attended'), ('Not attended', 'Not attended'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
