# Generated by Django 4.2.3 on 2023-08-20 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_alter_appointments_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslots',
            name='end',
            field=models.TimeField(null=True),
        ),
    ]
