# Generated by Django 4.2.3 on 2023-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_alter_timeslots_end'),
    ]

    operations = [
        migrations.AddField(
            model_name='timeslots',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
