# Generated by Django 4.2.3 on 2023-08-20 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_timeslots_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeslots',
            name='date',
            field=models.DateField(),
        ),
    ]
