# Generated by Django 4.2.3 on 2023-08-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_timeslots_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='is_approved',
        ),
        migrations.AlterField(
            model_name='appointments',
            name='amount_paid',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
