# Generated by Django 4.2.3 on 2023-08-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_remove_appointments_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='is_rescheduled',
            field=models.BooleanField(default=False),
        ),
    ]
