# Generated by Django 4.2.3 on 2023-08-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_appointments_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointments',
            name='link',
        ),
    ]
