# Generated by Django 4.2.3 on 2023-08-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_tasksubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubscription',
            name='validity',
            field=models.PositiveBigIntegerField(default=30),
        ),
    ]
