# Generated by Django 4.2.3 on 2023-08-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_tasksubscription_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubscription',
            name='validity',
            field=models.PositiveBigIntegerField(),
        ),
    ]
