# Generated by Django 4.2.3 on 2023-08-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_tasksubscription_validity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tasksubscription',
            old_name='date',
            new_name='subscribed_date',
        ),
        migrations.AddField(
            model_name='tasksubscription',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
