# Generated by Django 4.2.3 on 2023-08-16 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_rename_date_tasksubscription_subscribed_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubscription',
            name='expiry_date',
            field=models.DateField(),
        ),
    ]
