# Generated by Django 4.2.3 on 2023-08-16 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_tasksubscription_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasksubscription',
            name='expiry_date',
            field=models.DateField(null=True),
        ),
    ]
